# Generated by Django 3.2.12 on 2022-05-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("TODO", "0002_auto_20220529_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="userSet",
            field=models.ManyToManyField(to="users.User"),
        ),
    ]
